### ISSUE TITLE
您好，我想问一下在cudnn、pytorch、python和cuda等的版本要求是怎样的呢？谢谢

### ISSUE THREAD

**Issue by lijialei666** [sniklaus/pytorch-liteflownet#1]
您好，我想问一下在cudnn、pytorch、python和cuda等的版本要求是怎样的呢？谢谢

**Comment by sniklaus** [comment]
My apologies, but I am afraid that I do not speak Chinese.

**Comment by lijialei666** [comment]
oh! I'm sorry. I forgot that. I say that I want to know the version of the python, pytorch, cuda and cudnn. And you think others what I should be careful. thanks.

**Comment by sniklaus** [comment]
PyTorch 0.4.1 and newer should work. cuDNN is as far as I know already bundled with PyTorch, so there should not be any version conflict. CUDA 7.5 and newer should work, but that may depend on the version of CuPy.

Please let me know in case you have found any issues with this version information, thanks!

**Comment by lijialei666** [comment]
ok! Thank you very much!

**Comment by lijialei666** [comment]
Hello! I want to know whether did you upload the code for transfroming the format from .flo to .png, thanks!

**Comment by sniklaus** [comment]
I am afraid that the code in question originates from the Middlebury benchmark for optical flow, and I am not sure whether I am allowed to share it. However, you could get in touch with Daniel Scharstein and kindly ask him to share it with you as well.

**Comment by lijialei666** [comment]
I have got it. Thank you very much!

**Comment by sniklaus** [comment]
You are very welcome. I am closing this issue for now then, feel free to open it up again in case you have any additional questions.
