### ISSUE TITLE
Testing in new image pair

### ISSUE THREAD

**Issue by Yihan-Zhang** [sniklaus/pytorch-liteflownet#14]
Thanks for your great work!
When I want to use the code to test my own data, it reported error : 
python run.py --model default --first ../dataset/my_dataset/001.png --second ../dataset/my_dataset/002.png --out ./out.flo
Traceback (most recent call last):
  File "run.py", line 313, in <module>
    tensorOutput = estimate(tensorFirst, tensorSecond)
  File "run.py", line 290, in estimate
    tensorPreprocessedFirst = tensorFirst.cuda().view(1, 3, intHeight, intWidth)
RuntimeError: shape '[1, 3, 1080, 1920]' is invalid for input of size 8294400

How can I test with my own data?

**Comment by sniklaus** [comment]
`8294400 / 1920 / 1080 = 4`

Looks like your images have an alpha channel. Either remove that from the images directly or modify the provided such that it only uses the first three channels of an input image.
