### ISSUE TITLE
Could you please explain the meaning of the number you minus（0.411618, etc)？

### ISSUE THREAD

**Issue by Le1Elayne** [sniklaus/pytorch-liteflownet#18]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/33652055/65486298-a7bc1680-ded6-11e9-91a6-36d7354a00a8.png">
Could you please explain the meaning of the number you minus（0.41...,etc)？

**Comment by sniklaus** [comment]
During training, the "DataAugmentation" layer computes the mean over the first 3000 iterations as defined here: https://github.com/twhui/LiteFlowNet/blob/943a2cf24ed485a9c3fd1ee398e1d592ccdd031e/models/testing/deploy.prototxt#L62

During inference, we need to make sure to subtract this computed mean. Note that the mean is computed separately for the first and second image. As such, the mean values slightly differ.
