### ISSUE TITLE
How to see output of out.flo?

### ISSUE THREAD

**Issue by boheyse** [sniklaus/pytorch-liteflownet#20]
Once I do the run command:
`python run.py --model default --first ./images/0112.png --second ./images/0113.png --out ./out.flo`
I see the output, out.flo, but how do I visualize the results of the optical like in your comparison images.

Thanks in advance!

**Comment by sniklaus** [comment]
I am afraid that the code in question originates from the Middlebury benchmark for optical flow, and I am not sure whether I am allowed to share it. However, you could get in touch with Daniel Scharstein and kindly ask him to share it with you as well.

If you do not care about fully reproducing the shown visualization, it might be easier to use a different implementation though. You could, for example, adopt the visualization in the "Dense Optical Flow" section at the following link: https://docs.opencv.org/3.4.0/d7/d8b/tutorial_py_lucas_kanade.html
