### ISSUE TITLE
 AttributeError: module 'correlation' has no attribute 'FunctionCorrelation'

### ISSUE THREAD

**Issue by MSLAwan** [sniklaus/pytorch-liteflownet#21]
hello,
i have followed the steps as mentioned in usage but i got above error...
can you please guide me about reason for this error.
Regards

**Comment by sniklaus** [comment]
Does any of the following discussions help you to resolve this issue? Thanks!

https://github.com/sniklaus/pytorch-pwc/issues/12
https://github.com/sniklaus/pytorch-pwc/issues/19

**Comment by MSLAwan** [comment]
thankyou. it is solved
