### ISSUE TITLE
Help in modification of estimate () to deal batches

### ISSUE THREAD

**Issue by MFarooqAit** [sniklaus/pytorch-liteflownet#23]
Dear Sniklaus, 
Firstly, Thank you sharing the pytorch version for testing code of LiteFlowNet. 

I am trying to used your testing code of liteflownet and converting into a training code, but facing problem in handling batches instead of single image. Can you guide me how can i modify the estimate () function to deal with batches (batch size = 4).

Thank you in advance.

**Comment by sniklaus** [comment]
You should only have to modify the `estimate` function and call it accordingly, the implementation of the network should be able to handle arbitrary batch sizes.

https://github.com/sniklaus/pytorch-liteflownet/blob/072061947c3fe1ba3996682a7b2ec6973c737e33/run.py#L338-L363
