### ISSUE TITLE
How can I change the correlation maxdistance from 7 to 9?

### ISSUE THREAD

**Issue by SuperFreeMan-CXM** [sniklaus/pytorch-liteflownet#24]
Dear sniklaus, thank you for your great work.
I found liteflownet use 49(7x7) as correlation's patch size. How can I modify it?
If I want to use 81(9x9) as patch size, what should I do?

**Comment by sniklaus** [comment]
You would have to update the `correlation.py` file. This is not trivial though so I suggest you use a different implementation of the correlation part which exposes the necessary parameters, this one for example: https://github.com/ClementPinard/Pytorch-Correlation-extension
