### ISSUE TITLE
Correlation function

### ISSUE THREAD

**Issue by ShrutheeshIR** [sniklaus/pytorch-liteflownet#26]
Could you please explain what the correlation.py script does? I've seen it being used in Flownet2 and PWCNet as well. Can someone link a detailed explanation of the exact steps. I wish to write an equivalent code for CPU, and all current implementations require cuda.
Thanks

**Comment by sniklaus** [comment]
The first FlowNet paper has more details, see the first equation here: https://arxiv.org/abs/1504.06852

**Comment by bugczw** [comment]
@ShrutheeshIR I also have the same problem. Have you save this problem? 
In the project, the script _correlation.py_, uses a module called cupy. However, cupy is based on cuda, which means that it needs to contain GPU. Is there any method that does not use _cupy_ module to implement the correlation function?

**Comment by CJ0109** [comment]
@bugczw It seems that many people need the CPU implementation of the correlation module. Have you solved this problem now?
