### ISSUE TITLE
Check for pytorch >= 0.4.1 fails for pytorch built from git

### ISSUE THREAD

**Issue by abrock** [sniklaus/pytorch-liteflownet#28]
Hi,

Thank you for providing the implementation, it is very helpfull in my research and I'll make sure to cite you.

I built PyTorch from git and the run.py fails with an exception:

>  File "/home/alexander/promotion/pytorch-liteflownet/run.py", line 21, in <module>
>   assert(int(str('').join(torch.__version__.split('.')[0:3]).split('+')[0]) >= 41) # requires at least pytorch >version 0.4.1
>ValueError: invalid literal for int() with base 10: '140a0'

In my case the torch.__version__ is "1.4.0a0+5e8bac2", this seems to be automatically generated from the git commit of the pytorch repo I used to build: 5e8bac24b4c3b9abd0e056d663a9029cc79c44d5

I changed the check so it ignores the commit hash:

```import re
torch_major = torch.__version__.split('.')[0]
torch_minor = torch.__version__.split('.')[1]
torch_rev = re.sub("[^0-9].*", "", torch.__version__.split('.')[2]);
torch_version = int(str('').join([torch_major, torch_minor, torch_rev]))
print(torch_version)
assert(torch_version >= 41) # requires at least pytorch version 0.4.1
```

Of course this will fail if someone uses a very old (say, 0.3.1) version and the commit hash starts with a digit :-)

**Comment by sniklaus** [comment]
Thank you for your suggestion! I just fixed it in 207bf3ed216828ba3a182ecb10c259df3de1dda0 and simplified the solution by bumping the version to 1.0.0 (which is over a year old by now, so I am okay with this change).
