### ISSUE TITLE
NameError: name 'Stream' is not defined

### ISSUE THREAD

**Issue by mdyao** [sniklaus/pytorch-liteflownet#29]
It occurs the error "NameError: name 'Stream' is not defined" in /correlation/correlation.py #362.
and the compiler warns "Stream" is not defined. Where should I define this "Stream"?

**Comment by sniklaus** [comment]
Thank you for bringing this up! I just committed c28936af52c9597be6ff80c78766a2f68e6f3354 to address this problem and hence closing this issue for now. Please let me know in case you continue to have this or any other issues, thanks!
