### ISSUE TITLE
Need guidance regarding writing the training code

### ISSUE THREAD

**Issue by MFarooqAit** [sniklaus/pytorch-liteflownet#31]
Dear Simon Niklaus,
Thank you so much for sharing the testing code for liteflownet.

I tried to write the training code of liteflownet by modifying your testing code.
I enablebed gradient computation  **torch.set_grad_enabled(True)** and did other necessary changes, but found **RuntimeError: CUDA error: out of memory** at following line in "class Regularization"
tensorDist = self.moduleDist(self.moduleMain(torch.cat([ tensorDifference, tensorFlow - tensorFlow.view(tensorFlow.size(0), 2, -1).mean(2, True).view(tensorFlow.size(0), 2, 1, 1), self.moduleFeat(tensorFeaturesFirst) ], 1)))

Can you guide, how can i fix this problem.
Best,
Farooq

**Comment by sniklaus** [comment]
Looks like you are running out of memory, so you could use a GPU with more memory or reduce the batch size. I am afraid that I am unable to dedicate my scarce spare time in supporting you with your training efforts though, my apologies.

**Comment by MFarooqAit** [comment]
Dear Simon Niklaus,
Thank you so much for reply. Ok no problem. 

I have already used batch_size = 1 and also deleted the intermediate variables in the training loop.
I am trying to reduce the tensor sizes and may able to fix this issue. Thanks!
Best,
Farooq

**Comment by sniklaus** [comment]
The next step would probably trying to reduce the input size (training on patches of 256 by 256 pixels is usually a good start). Good luck!

**Comment by MFarooqAit** [comment]
Dear Simon Niklaus,
Thank you so much for useful feedback. Okay i try to reduce the input size. Thank again!
Best, 
Farooq
