### ISSUE TITLE
What are the differences between these 3 pre-trained models？

### ISSUE THREAD

**Issue by DonaldKam** [sniklaus/pytorch-liteflownet#33]
wget --verbose --continue --timestamping http://content.sniklaus.com/github/pytorch-liteflownet/network-default.pytorch
wget --verbose --continue --timestamping http://content.sniklaus.com/github/pytorch-liteflownet/network-kitti.pytorch
wget --verbose --continue --timestamping http://content.sniklaus.com/github/pytorch-liteflownet/network-sintel.pytorch

**Comment by sniklaus** [comment]
You can find more information about them here: https://github.com/twhui/LiteFlowNet#trained-models
