### ISSUE TITLE
liteflownet2 pytorch implementation

### ISSUE THREAD

**Issue by steve13durant** [sniklaus/pytorch-liteflownet#35]
Could I know whether you tried to implement liteflownet2 by pytorch?

**Comment by sniklaus** [comment]
I am afraid not, I just haven't had the time yet. It also seems unlikely that I will find the time to port LiteFlowNet2 to PyTorch anytime soon. If you do not want to use Caffe then your best option for running LiteFlowNet2 seems to be: https://github.com/rogerhcheng/LiteFlowNet2-TF2
