### ISSUE TITLE
Greyscale Images

### ISSUE THREAD

**Issue by andreitapch** [sniklaus/pytorch-liteflownet#39]
Hi, thanks for your implementation. I used first with Sintel database and it work good, after I tried to use it with a personal dataset of greyscale images, but it has not been posible to make it work, any suggestions?

Thanks.

**Comment by sniklaus** [comment]
Try converting the grayscale image to an RGB image by replicating the gray channel 3 times. It will still be grayscale and the network may not predict good results on grayscale images in general, but at least the format would match what the network expects.
