### ISSUE TITLE
 Question for liteflownet

### ISSUE THREAD

**Issue by XQLuck** [sniklaus/pytorch-liteflownet#41]
I  have tested  your pytorch-liteflownet and get the results, but how can I  train the pytroch-liteflownet on a new dataset?  Hope to get your reply ~~~thanks

**Comment by sniklaus** [comment]
I am afraid that this repository focuses on replicating the inference of the official LiteFlowNet implementation, and it does not make any efforts to replicate the training. My apologies that I will thus not be able to assist you in your training efforts.
