### ISSUE TITLE
In place operation error when backpropagating

### ISSUE THREAD

**Issue by surajsy** [sniklaus/pytorch-liteflownet#42]
![anydesk00000 (2)](https://user-images.githubusercontent.com/56350813/100415629-a110cc80-30a2-11eb-9aeb-0be2232924de.png)

I tried to fine tune the model using warped image as supervision on custom dataset. I get this in place operation error in one of the convolution layer. 

I didn't see this issue when I replaced LiteFlowNet with PwC Net. Any thoughts on why this may be occuring?

**Comment by sniklaus** [comment]
I am afraid that I cannot help you whit this issue, my apologies. You must have made changes to the code (the line numbers do not match what it is in this repository), so I am unable to look into this further.
