### ISSUE TITLE
what‘s  pretrained models name?

### ISSUE THREAD

**Issue by WangPeng19981204** [sniklaus/pytorch-liteflownet#44]
Hi Niklaus,
Thanks for providing a clean implementaion of Litefloenet on pytorch.
I am learning flownet with your code, i am confused that the name of pretrained models are not given，so that i can only use default model you mentioned to test ,Could you please list the name of pretrained models and  Explain these models  are trained on what data sets，thank you.

**Comment by sniklaus** [comment]
Thanks for the heads-up!

There used to be a [`download.bash`](https://github.com/sniklaus/pytorch-liteflownet/blob/768367254ccc83c3f5b145f8801255e40f99a52e/download.bash) to download the model files so it was obvious which ones are available. However, I have changed the code to download the models on the fly, which is a little more convenient. I thus just added the following comment to make it clear again what is available.

https://github.com/sniklaus/pytorch-liteflownet/blob/d1540c5966d9470821d561d55840485b7593e3f1/run.py#L29

For more information on these models, please see: https://github.com/twhui/LiteFlowNet#trained-models
