### ISSUE TITLE
网络模型文件

### ISSUE THREAD

**Issue by dawei03896** [sniklaus/pytorch-liteflownet#45]
大佬你好，我想用你的pytorch-liteflownet工程提取一下光流，但是在工程内没有发现liteflownet的pytorch测试模型，想请教一下这个工程时怎么使用的？非常感谢。

**Comment by sniklaus** [comment]
The model weights are downloaded on the fly using `torch.hub.load_state_dict_from_url(...)`.

https://github.com/sniklaus/pytorch-liteflownet/blob/dccd875d8364d351572c5f4bfbcbd30752fd28f3/run.py#L299

**Comment by aiguo112** [comment]
Hi, when i run this command  **python run.py --model default --first ./images/first.png --second ./images/second.png --out ./out.flo**

i get the following typeError.

File "run.py", line 299, in __init__
    self.load_state_dict({ strKey.replace('module', 'net'): tenWeight for strKey, tenWeight in torch.hub.load_state_dict_from_url(url='http://content.sniklaus.com/github/pytorch-liteflownet/network-' + arguments_strModel + '.pytorch', file_name='liteflownet-' + arguments_strModel).items() })
TypeError: load_state_dict_from_url() got an unexpected keyword argument '**file_name**'

**Comment by sniklaus** [comment]
Update your PyTorch to version `1.6.0` or higher and let me know in case that didn't resolve the issue, thanks!
