### ISSUE TITLE
run liteflownet on a sequence of pairs (aka video) offline/real time.

### ISSUE THREAD

**Issue by ilinii** [sniklaus/pytorch-liteflownet#49]
Hello, 
I've tested the code, yet I have a question, is there any possible way to run the code on a video instead of two frames without running a bash script that executes the command every single 2 frames ? if so, can the model provide good results for real time live feed ? I'm using a Jetson Nano.
Thanks in advance.

**Comment by sniklaus** [comment]
You can just change the Python script to ingest a stream of frames and predict the flow between them, yes. I am afraid that I do not know enough about the Jetson Nano (and which resolution/fps you are targeting) to comment on your second question.
