### ISSUE TITLE
What is dblBackward?

### ISSUE THREAD

**Issue by wuwenhuan** [sniklaus/pytorch-liteflownet#6]
thank you for your pytorch codes !
However, for the code: self.dblBackward = [ 0.0, 0.0, 10.0, 5.0, 2.5, 1.25, 0.625 ][intLevel], 
why  is self.dblBackward set to be 10 when intLevel=2 ? why  is self.dblBackward set to be 5.0 when intLevel=3 ?  etc.
I think the dblBackward should be the scale of downsample since tensorFlow=tensorFlow * self.dblBackward.

**Comment by sniklaus** [comment]
One way to think about it is that if we upscale the flow by a factor of 2 then the magnitude should be scaled by a factor of 2 as well (since everything is twice as far apart now). Also please see: https://github.com/twhui/LiteFlowNet/issues/15

**Comment by wuwenhuan** [comment]
thank you very much!

**Comment by wuwenhuan** [comment]
@
