### ISSUE TITLE
Why is the resolution of the output of the optical flow  inferred with liteflownet half of the original image pair?

### ISSUE THREAD

**Issue by wuwenhuan** [sniklaus/pytorch-liteflownet#9]
For the Liteflownet,  the resolution of the output of the optical flow when inferring with liteflownet is the half of the original image pair,  and then the output is upsampled  to the same size as the original image. However, why not directly output the optical flow whose  size is the same as the original image?  And I notice that PWC-Net also uses the similar manner. Thank you!

**Comment by sniklaus** [comment]
It is probably easier to train the model at a coarse resolution (since everything is essentially closer together in terms of pixels). For a more detailed explanation, you may want to consider asking your question in the official repository of LiteFlowNet: https://github.com/twhui/LiteFlowNet/issues

**Comment by wuwenhuan** [comment]
Thank you very much for your reply !
